import React, { useEffect, useState } from 'react';

const glyphs: Record<string, string> = { home: '⌂', grid: '▦', bookmark: '🔖', search: '⌕', user: '◉', arrow: '←', book: '▤', clock: '◷', share: '↗', sun: '☀', moon: '☾' };
export function Icon({ name, size = 18 }: { name: string; size?: number }) { return React.createElement('span', { 'aria-hidden': true, style: { fontSize: size, lineHeight: 1 } }, glyphs[name] ?? '•'); }
export function ThemeToggle() { const [dark, setDark] = useState(true); useEffect(() => setDark(document.documentElement.dataset.theme !== 'light'), []); return React.createElement('button', { className: 'icon-button', type: 'button', 'aria-label': 'تغییر پوسته', onClick: () => { const next = !dark; setDark(next); document.documentElement.dataset.theme = next ? 'dark' : 'light'; localStorage.setItem('city-perspectives:theme', next ? 'dark' : 'light'); } }, React.createElement(Icon, { name: dark ? 'sun' : 'moon' })); }
export function PostActions({ id, title, path }: { id: string; title: string; path: string }) { const [saved, setSaved] = useState(false); useEffect(() => setSaved(JSON.parse(localStorage.getItem('rozaneh:saved') ?? '[]').includes(id)), [id]); return React.createElement('button', { className: 'icon-button', type: 'button', 'aria-label': saved ? 'حذف نشانک' : 'ذخیره مطلب', onClick: async () => { const values: string[] = JSON.parse(localStorage.getItem('rozaneh:saved') ?? '[]'); const next = values.includes(id) ? values.filter(x => x !== id) : [...values, id]; localStorage.setItem('rozaneh:saved', JSON.stringify(next)); setSaved(next.includes(id)); } }, saved ? '★' : '☆'); }
export function EpisodeStatus({ id }: { id: string }) { return React.createElement('span', { className: 'episode-status', 'data-post': id }, 'خوانده نشده'); }
export function ReadingTools({ id }: { id: string }) { return React.createElement('div', { className: 'reading-tools' }, React.createElement('button', { type: 'button', onClick: () => document.body.classList.toggle('focus-reading') }, 'حالت تمرکز')); }
export function Comments({ slug }: { slug: string }) { return React.createElement('section', { className: 'comments', 'aria-label': 'یادداشت‌ها' }, React.createElement('h2', null, 'یادداشت‌ها'), React.createElement('p', null, 'بخش گفت‌وگو در نسخهٔ عمومیِ سبک فعال نیست.')); }
export function ReadingAssistant() { return null; }
export function SavedPosts({ posts }: { posts: { id: string; title: string; slug: string }[] }) { const [saved, setSaved] = useState<string[]>([]); useEffect(() => setSaved(JSON.parse(localStorage.getItem('rozaneh:saved') ?? '[]')), []); const matches = posts.filter(p => saved.includes(p.id)); return React.createElement('section', { className: 'saved-posts' }, matches.length ? matches.map(p => React.createElement('a', { key: p.id, href: `/posts/${p.slug}`, className: 'list-card' }, p.title)) : React.createElement('p', { className: 'muted' }, 'هنوز مطلبی ذخیره نکرده‌ای.')) }
